In [ ]:
# import geopandas as gpd
# import pandas as pd
# from pathlib import Path
# from concurrent.futures import ThreadPoolExecutor
# import time

# # Pfad zum OSM-Ordner
# osm_folder = Path("data/osm")

# # Alle PBF-Dateien finden
# pbf_files = sorted([f for f in osm_folder.glob("processed_highways_*.pbf")])

# print(f"Gefundene PBF-Dateien: {len(pbf_files)}")
# for f in pbf_files:
#     print(f"  - {f.name}")

# # Funktion zum Laden einer einzelnen PBF-Datei
# def load_pbf(pbf_file):
#     try:
#         #gdf = gpd.read_file(pbf_file, layer="lines", columns=["geometry", "name", "highway"])
#         gdf = gpd.read_file(pbf_file, layer="lines")
#         gdf["region"] = pbf_file.stem.split("_")[-2]  # z.B. "DE-BB" extrahieren
#         print(f"  ✓ {pbf_file.name}: {len(gdf)} Zeilen geladen")
#         return gdf
#     except Exception as e:
#         print(f"  ✗ {pbf_file.name}: Fehler: {e}")
#         return None

# # Paralleles Laden mit ThreadPoolExecutor
# start = time.time()
# print("\nLade PBF-Dateien parallel...")
# with ThreadPoolExecutor(max_workers=4) as executor:
#     gdfs = [gdf for gdf in executor.map(load_pbf, pbf_files) if gdf is not None]

# # Zu einem GeoDataFrame kombinieren
# gdf_all = pd.concat(gdfs, ignore_index=True)
# elapsed = time.time() - start

# print(f"\n✓ Fertig in {elapsed:.1f}s")
# print(f"Gesamt: {len(gdf_all)} Zeilen")
# print(f"Spalten: {list(gdf_all.columns)}")
# print(f"Regionen: {gdf_all['region'].unique()}")

Gefundene PBF-Dateien: 16
  - processed_highways_DE-BB_latest.pbf
  - processed_highways_DE-BE_latest.pbf
  - processed_highways_DE-BW_latest.pbf
  - processed_highways_DE-BY_latest.pbf
  - processed_highways_DE-HB_latest.pbf
  - processed_highways_DE-HE_latest.pbf
  - processed_highways_DE-HH_latest.pbf
  - processed_highways_DE-MV_latest.pbf
  - processed_highways_DE-NI_latest.pbf
  - processed_highways_DE-NW_latest.pbf
  - processed_highways_DE-RP_latest.pbf
  - processed_highways_DE-SH_latest.pbf
  - processed_highways_DE-SL_latest.pbf
  - processed_highways_DE-SN_latest.pbf
  - processed_highways_DE-ST_latest.pbf
  - processed_highways_DE-TH_latest.pbf

Lade PBF-Dateien parallel...
  ✓ processed_highways_DE-BB_latest.pbf: 1089149 Zeilen geladen
  ✓ processed_highways_DE-BW_latest.pbf: 2317747 Zeilen geladen
  ✓ processed_highways_DE-BY_latest.pbf: 3125917 Zeilen geladen
  ✓ processed_highways_DE-BE_latest.pbf: 458218 Zeilen geladen
  ✓ processed_highways_DE-HB_latest.pbf: 71349 Zeilen geladen
  ✓ processed_highways_DE-MV_latest.pbf: 362113 Zeilen geladen
  ✓ processed_highways_DE-HH_latest.pbf: 209828 Zeilen geladen
  ✓ processed_highways_DE-HE_latest.pbf: 1159115 Zeilen geladen
  ✓ processed_highways_DE-SH_latest.pbf: 491273 Zeilen geladen
  ✓ processed_highways_DE-RP_latest.pbf: 901607 Zeilen geladen
  ✓ processed_highways_DE-NW_latest.pbf: 2631217 Zeilen geladen
  ✓ processed_highways_DE-ST_latest.pbf: 488644 Zeilen geladen  ✓ processed_highways_DE-SL_latest.pbf: 156265 Zeilen geladen

  ✓ processed_highways_DE-SN_latest.pbf: 931210 Zeilen geladen
  ✓ processed_highways_DE-TH_latest.pbf: 536043 Zeilen geladen
  ✓ processed_highways_DE-NI_latest.pbf: 1616581 Zeilen geladen

✓ Fertig in 354.6s
Gesamt: 16546276 Zeilen
Spalten: ['osm_id', 'name', 'highway', 'waterway', 'aerialway', 'barrier', 'man_made', 'railway', 'z_order', 'other_tags', 'geometry', 'region']
Regionen: ['DE-BB' 'DE-BE' 'DE-BW' 'DE-BY' 'DE-HB' 'DE-HE' 'DE-HH' 'DE-MV' 'DE-NI'
 'DE-NW' 'DE-RP' 'DE-SH' 'DE-SL' 'DE-SN' 'DE-ST' 'DE-TH']

In [ ]:
# gdf_all.to_parquet("data/osm/all_highways.parquet", index=False)

In [1]:
import geopandas as gpd
import pandas as pd
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
import time

In [4]:
gdf_all=gpd.read_parquet("data/osm/all_highways.parquet")

In [5]:
coverage_data = pd.read_csv("data/germany_osm-highways_mp-coverage_latest.csv")

In [6]:
coverage_data.head()

       osm_id mapillary_coverage
0  1450732492               pano
1  1095301604               pano
2  1095300976               pano
3  1095300975               pano
4  1095202209               pano

In [7]:
# prepare merge

gdf_all.osm_id = gdf_all.osm_id.astype(int)
coverage_data.osm_id = coverage_data.osm_id.astype(int)

In [8]:
# merge
merged_gdf = gdf_all.merge(coverage_data, on="osm_id", how="left")

In [9]:
merged_gdf

,osm_id,name,highway,waterway,aerialway,barrier,man_made,railway,z_order,other_tags,geometry,region,mapillary_coverage
0,3996955,None,motorway,None,None,None,None,None,9,"""check_date:lit""=>""2021-04-06"",""embankment""=>""...","LINESTRING (13.09264 52.31368, 13.09376 52.315...",DE-BB,regular
1,3996957,None,motorway,None,None,None,None,None,9,"""destination:arrow:lanes""=>""through|through|th...","LINESTRING (13.09522 52.3023, 13.09285 52.30184)",DE-BB,pano
2,4040461,None,motorway,None,None,None,None,None,9,"""int_ref""=>""E 26"",""lanes""=>""2"",""lit""=>""no"",""ma...","LINESTRING (11.92993 53.3017, 11.92475 53.3032...",DE-BB,pano
3,4040465,None,motorway,None,None,None,None,None,9,"""int_ref""=>""E 26"",""lanes""=>""2"",""lit""=>""no"",""ma...","LINESTRING (12.06881 53.28689, 12.06785 53.287...",DE-BB,regular
4,4040467,None,motorway,None,None,None,None,None,9,"""int_ref""=>""E 26"",""lanes""=>""2"",""lit""=>""no"",""ma...","LINESTRING (12.13879 53.26535, 12.13794 53.265...",DE-BB,regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16546271,1475095963,None,steps,None,None,None,None,None,0,"""access""=>""private""","LINESTRING (10.73222 50.82282, 10.73231 50.82281)",DE-TH,NaN
16546272,1475095964,None,footway,None,None,None,None,None,0,"""access""=>""private""","LINESTRING (10.73243 50.82301, 10.73267 50.82296)",DE-TH,NaN
16546273,1475095965,None,steps,None,None,None,None,None,0,"""access""=>""private""","LINESTRING (10.73287 50.82273, 10.7328 50.82274)",DE-TH,NaN
16546274,1475095966,None,steps,None,None,None,None,None,0,"""access""=>""private""","LINESTRING (10.73285 50.82268, 10.73278 50.82269)",DE-TH,NaN
16546275,1475095970,None,footway,None,None,None,None,None,0,"""access""=>""private""","LINESTRING (10.73231 50.82303, 10.73236 50.823...",DE-TH,NaN

In [10]:
merged_gdf_clean=merged_gdf[["osm_id", "highway", "region", "mapillary_coverage", "geometry"]].copy()

In [13]:
#merged_gdf_clean.highway.unique()

In [14]:
merged_gdf_clean_majorRoads=merged_gdf_clean[merged_gdf_clean.highway.isin(['motorway', 'motorway_link',
                                                'trunk', 'trunk_link', 
                                                "primary", "primary_link", 
                                                "secondary", "secondary_link", 
                                                "tertiary", "tertiary_link", 
                                                ])].copy()

In [15]:
merged_gdf_clean_majorRoads

,osm_id,highway,region,mapillary_coverage,geometry
0,3996955,motorway,DE-BB,regular,"LINESTRING (13.09264 52.31368, 13.09376 52.315..."
1,3996957,motorway,DE-BB,pano,"LINESTRING (13.09522 52.3023, 13.09285 52.30184)"
2,4040461,motorway,DE-BB,pano,"LINESTRING (11.92993 53.3017, 11.92475 53.3032..."
3,4040465,motorway,DE-BB,regular,"LINESTRING (12.06881 53.28689, 12.06785 53.287..."
4,4040467,motorway,DE-BB,regular,"LINESTRING (12.13879 53.26535, 12.13794 53.265..."
...,...,...,...,...,...
16546196,1474827547,tertiary,DE-TH,NaN,"LINESTRING (12.57312 50.92311, 12.57347 50.9231)"
16546219,1474895413,tertiary,DE-TH,NaN,"LINESTRING (9.86663 50.68385, 9.86676 50.6839,..."
16546241,1475048515,tertiary,DE-TH,NaN,"LINESTRING (12.46595 50.94996, 12.46601 50.94997)"
16546242,1475048516,tertiary,DE-TH,NaN,"LINESTRING (12.47406 50.97261, 12.47432 50.972..."
16546245,1475048520,tertiary,DE-TH,NaN,"LINESTRING (12.49239 50.9969, 12.4925 50.99682..."

In [16]:
kreise=gpd.read_file("https://raw.githubusercontent.com/isellsoap/deutschlandGeoJSON/refs/heads/main/4_kreise/1_sehr_hoch.geo.json")
bland=gpd.read_file("https://raw.githubusercontent.com/isellsoap/deutschlandGeoJSON/refs/heads/main/2_bundeslaender/1_sehr_hoch.geo.json")

In [17]:
#kreise
#bland

In [18]:
kreise.rename(columns={"NAME_1":"Bundesland","NAME_3": "Landkreis"}, inplace=True)
bland.rename(columns={"name":"Bundesland"}, inplace=True)

In [20]:
target_crs = 25832
lines = merged_gdf_clean_majorRoads.to_crs(target_crs)
kreise  = kreise.to_crs(target_crs)  # kreise: Polygon-GDF mit Spalte "Landkreis"

In [21]:
pts = lines[["osm_id", "geometry"]].copy()
pts["geometry"] = pts.geometry.representative_point()

In [22]:
joined = pts.sjoin(
    kreise[["Landkreis","Bundesland", "geometry"]],
    how="left",
    predicate="within",
)

In [23]:
lines = lines.merge(
    joined[["osm_id", "Landkreis","Bundesland"]],
    on="osm_id",
    how="left",
)

In [24]:
lines["length_m"] = lines.geometry.length

In [25]:
lines

,osm_id,highway,region,mapillary_coverage,geometry,Landkreis,Bundesland,length_m
0,3996955,motorway,DE-BB,regular,"LINESTRING (778933.815 5803816.85, 778999.282 ...",Potsdam-Mittelmark,Brandenburg,489.512134
1,3996957,motorway,DE-BB,pano,"LINESTRING (779181.582 5802561.592, 779023.187...",Potsdam-Mittelmark,Brandenburg,169.464392
2,4040461,motorway,DE-BB,pano,"LINESTRING (695230.778 5909836.658, 694878.545...",Parchim,Mecklenburg-Vorpommern,2089.505867
3,4040461,motorway,DE-BB,pano,"LINESTRING (695230.778 5909836.658, 694878.545...",Parchim,Mecklenburg-Vorpommern,2089.505867
4,4040465,motorway,DE-BB,regular,"LINESTRING (704553.042 5908579.118, 704487.691...",Prignitz,Brandenburg,5345.608668
...,...,...,...,...,...,...,...,...
1606488,1474895413,tertiary,DE-TH,NaN,"LINESTRING (561223.013 5615027.469, 561232.308...",Fulda,Hessen,614.275539
1606489,1474895413,tertiary,DE-TH,NaN,"LINESTRING (561223.013 5615027.469, 561232.308...",Fulda,Hessen,614.275539
1606490,1475048515,tertiary,DE-TH,NaN,"LINESTRING (743434.92 5649981.946, 743439.38 5...",Altenburger Land,Thüringen,4.590947
1606491,1475048516,tertiary,DE-TH,NaN,"LINESTRING (743885.838 5652526.263, 743904.698...",Altenburger Land,Thüringen,151.444109
1606492,1475048520,tertiary,DE-TH,NaN,"LINESTRING (745044.271 5655286.864, 745052.248...",Altenburger Land,Thüringen,177.770705

In [83]:

df = lines.copy()

# NaN explizit
df["mapillary_coverage"] = df["mapillary_coverage"].fillna("NaN")

# _link entfernen → motorway_link → motorway
df["highway"] = df["highway"].str.replace("_link$", "", regex=True)

In [84]:
df

,osm_id,highway,region,mapillary_coverage,geometry,Landkreis,Bundesland,length_m
0,3996955,motorway,DE-BB,regular,"LINESTRING (778933.815 5803816.85, 778999.282 ...",Potsdam-Mittelmark,Brandenburg,489.512134
1,3996957,motorway,DE-BB,pano,"LINESTRING (779181.582 5802561.592, 779023.187...",Potsdam-Mittelmark,Brandenburg,169.464392
2,4040461,motorway,DE-BB,pano,"LINESTRING (695230.778 5909836.658, 694878.545...",Parchim,Mecklenburg-Vorpommern,2089.505867
3,4040461,motorway,DE-BB,pano,"LINESTRING (695230.778 5909836.658, 694878.545...",Parchim,Mecklenburg-Vorpommern,2089.505867
4,4040465,motorway,DE-BB,regular,"LINESTRING (704553.042 5908579.118, 704487.691...",Prignitz,Brandenburg,5345.608668
...,...,...,...,...,...,...,...,...
1606488,1474895413,tertiary,DE-TH,NaN,"LINESTRING (561223.013 5615027.469, 561232.308...",Fulda,Hessen,614.275539
1606489,1474895413,tertiary,DE-TH,NaN,"LINESTRING (561223.013 5615027.469, 561232.308...",Fulda,Hessen,614.275539
1606490,1475048515,tertiary,DE-TH,NaN,"LINESTRING (743434.92 5649981.946, 743439.38 5...",Altenburger Land,Thüringen,4.590947
1606491,1475048516,tertiary,DE-TH,NaN,"LINESTRING (743885.838 5652526.263, 743904.698...",Altenburger Land,Thüringen,151.444109
1606492,1475048520,tertiary,DE-TH,NaN,"LINESTRING (745044.271 5655286.864, 745052.248...",Altenburger Land,Thüringen,177.770705

In [85]:
##### AB Hier muss man sich entscheiden, ob man die Daten auf Kreisebene oder Bundeslandebene analysieren möchte.

In [86]:
#r_einheit="Landkreis" 
r_einheit="Bundesland"

In [87]:
agg = (
    df.groupby([r_einheit, "highway", "mapillary_coverage"], observed=True)["length_m"]
      .sum()
      .reset_index()
)

agg["total_length"] = (
    agg.groupby([r_einheit, "highway"])["length_m"]
       .transform("sum")
)

agg["share"] = agg["length_m"] / agg["total_length"]

In [88]:
agg

,Bundesland,highway,mapillary_coverage,length_m,total_length,share
0,Baden-Württemberg,motorway,NaN,1.681342e+05,2.736012e+06,0.061452
1,Baden-Württemberg,motorway,pano,2.017589e+05,2.736012e+06,0.073742
2,Baden-Württemberg,motorway,regular,2.366119e+06,2.736012e+06,0.864806
3,Baden-Württemberg,primary,NaN,1.343935e+06,4.421474e+06,0.303956
4,Baden-Württemberg,primary,pano,5.081578e+05,4.421474e+06,0.114930
...,...,...,...,...,...,...
230,Thüringen,tertiary,pano,9.502418e+04,4.504041e+06,0.021098
231,Thüringen,tertiary,regular,4.570822e+05,4.504041e+06,0.101483
232,Thüringen,trunk,NaN,6.423610e+04,2.588024e+05,0.248205
233,Thüringen,trunk,pano,1.111397e+04,2.588024e+05,0.042944
234,Thüringen,trunk,regular,1.834524e+05,2.588024e+05,0.708851

In [89]:
agg_all = (
    df.groupby([r_einheit, "mapillary_coverage"], observed=True)["length_m"]
      .sum()
      .reset_index()
)

agg_all["total_length"] = (
    agg_all.groupby(r_einheit)["length_m"]
           .transform("sum")
)

agg_all["share"] = agg_all["length_m"] / agg_all["total_length"]

# highway-Spalte ergänzen
agg_all["highway"] = "all"

In [90]:
#agg_all

In [91]:
agg_combined = pd.concat([agg, agg_all], ignore_index=True)

In [92]:
agg_combined

,Bundesland,highway,mapillary_coverage,length_m,total_length,share
0,Baden-Württemberg,motorway,NaN,1.681342e+05,2.736012e+06,0.061452
1,Baden-Württemberg,motorway,pano,2.017589e+05,2.736012e+06,0.073742
2,Baden-Württemberg,motorway,regular,2.366119e+06,2.736012e+06,0.864806
3,Baden-Württemberg,primary,NaN,1.343935e+06,4.421474e+06,0.303956
4,Baden-Württemberg,primary,pano,5.081578e+05,4.421474e+06,0.114930
...,...,...,...,...,...,...
277,Schleswig-Holstein,all,pano,4.999339e+05,1.162269e+07,0.043014
278,Schleswig-Holstein,all,regular,4.776243e+06,1.162269e+07,0.410941
279,Thüringen,all,NaN,8.551003e+06,1.265548e+07,0.675676
280,Thüringen,all,pano,4.474363e+05,1.265548e+07,0.035355
281,Thüringen,all,regular,3.657041e+06,1.265548e+07,0.288969

In [93]:
# result = (
#     agg_combined
#       .pivot(
#           index=[r_einheit, "highway"],
#           columns="mapillary_coverage",
#           values="share"
#       )
#       .fillna(0)
#       .reset_index()
# )


cov_order = ["NaN", "pano", "regular"]

df = agg_combined.copy()

# NaN in mapillary_coverage als Kategorie behandeln
df["mapillary_coverage"] = df["mapillary_coverage"].astype("string").fillna("NaN")

# 1) Shares
share_wide = (
    df.pivot_table(
        index=[r_einheit, "highway"],
        columns="mapillary_coverage",
        values="share",
        aggfunc="sum",
        fill_value=0,
    )
)

# 2) Längen in km (auf 1 Nachkommastelle runden)
length_wide = (
    df.pivot_table(
        index=[r_einheit, "highway"],
        columns="mapillary_coverage",
        values="length_m",
        aggfunc="sum",
        fill_value=0,
    )
    .div(1000.0)
    .round(1)
)

# fehlende Spalten absichern + Reihenfolge
for c in cov_order:
    if c not in share_wide.columns:
        share_wide[c] = 0
    if c not in length_wide.columns:
        length_wide[c] = 0

share_wide = share_wide[cov_order].add_prefix("share_")
length_wide = length_wide[cov_order].add_prefix("length_")

result = pd.concat([share_wide, length_wide], axis=1).reset_index()

In [94]:
result

mapillary_coverage,Bundesland,highway,share_NaN,share_pano,share_regular,length_NaN,length_pano,length_regular
0,Baden-Württemberg,all,0.540374,0.076582,0.383045,18627.5,2639.9,13204.2
1,Baden-Württemberg,motorway,0.061452,0.073742,0.864806,168.1,201.8,2366.1
2,Baden-Württemberg,primary,0.303956,0.114930,0.581114,1343.9,508.2,2569.4
3,Baden-Württemberg,secondary,0.574752,0.074611,0.350637,6613.7,858.5,4034.8
4,Baden-Württemberg,tertiary,0.714741,0.073924,0.211334,10183.2,1053.2,3011.0
...,...,...,...,...,...,...,...,...
91,Thüringen,motorway,0.108271,0.097967,0.793763,142.0,128.5,1040.8
92,Thüringen,primary,0.512104,0.040895,0.447000,845.2,67.5,737.8
93,Thüringen,secondary,0.719472,0.029476,0.251052,3547.6,145.3,1237.9
94,Thüringen,tertiary,0.877420,0.021098,0.101483,3951.9,95.0,457.1
95,Thüringen,trunk,0.248205,0.042944,0.708851,64.2,11.1,183.5

In [95]:
order = ["motorway", "trunk", "primary", "secondary", "tertiary", "all"]
result["highway"] = pd.Categorical(result["highway"], order, ordered=True)
result = result.sort_values([r_einheit, "highway"])

In [96]:
result

mapillary_coverage,Bundesland,highway,share_NaN,share_pano,share_regular,length_NaN,length_pano,length_regular
1,Baden-Württemberg,motorway,0.061452,0.073742,0.864806,168.1,201.8,2366.1
5,Baden-Württemberg,trunk,0.204265,0.011665,0.784070,318.6,18.2,1222.9
2,Baden-Württemberg,primary,0.303956,0.114930,0.581114,1343.9,508.2,2569.4
3,Baden-Württemberg,secondary,0.574752,0.074611,0.350637,6613.7,858.5,4034.8
4,Baden-Württemberg,tertiary,0.714741,0.073924,0.211334,10183.2,1053.2,3011.0
...,...,...,...,...,...,...,...,...
95,Thüringen,trunk,0.248205,0.042944,0.708851,64.2,11.1,183.5
92,Thüringen,primary,0.512104,0.040895,0.447000,845.2,67.5,737.8
93,Thüringen,secondary,0.719472,0.029476,0.251052,3547.6,145.3,1237.9
94,Thüringen,tertiary,0.877420,0.021098,0.101483,3951.9,95.0,457.1
90,Thüringen,all,0.675676,0.035355,0.288969,8551.0,447.4,3657.0

In [97]:
r = result.copy().rename(columns={
    "share_NaN": "share_no_cover",
    "length_NaN": "length_no_cover",
})

wide_long = r.melt(
    id_vars=[r_einheit, "highway"],
    value_vars=[
        "share_no_cover", "share_pano", "share_regular",
        "length_no_cover", "length_pano", "length_regular",
    ],
    var_name="metric_coverage",
    value_name="value",
)

wide_long[["metric", "coverage"]] = wide_long["metric_coverage"].str.split("_", n=1, expand=True)

# FIX: Categorical -> string
wide_long["col"] = (
    wide_long["highway"].astype("string")
    + "_" + wide_long["metric"].astype("string")
    + "_" + wide_long["coverage"].astype("string")
)

wide = (
    wide_long.pivot(index=r_einheit, columns="col", values="value")
             .fillna(0)
             .reset_index()
)

wide.head()

col,Bundesland,all_length_no_cover,all_length_pano,all_length_regular,all_share_no_cover,all_share_pano,all_share_regular,motorway_length_no_cover,motorway_length_pano,motorway_length_regular,...,tertiary_length_regular,tertiary_share_no_cover,tertiary_share_pano,tertiary_share_regular,trunk_length_no_cover,trunk_length_pano,trunk_length_regular,trunk_share_no_cover,trunk_share_pano,trunk_share_regular
0,Baden-Württemberg,18627.5,2639.9,13204.2,0.540374,0.076582,0.383045,168.1,201.8,2366.1,...,3011.0,0.714741,0.073924,0.211334,318.6,18.2,1222.9,0.204265,0.011665,0.784070
1,Bayern,35392.3,3747.1,15553.2,0.647114,0.068512,0.284374,476.7,1536.3,4313.9,...,3133.9,0.837662,0.030283,0.132055,581.9,128.5,914.8,0.358021,0.079083,0.562895
2,Berlin,1196.1,4596.9,2890.1,0.137750,0.529409,0.332841,160.7,403.1,366.9,...,681.2,0.203826,0.515951,0.280223,14.8,1.6,30.3,0.317660,0.033684,0.648656
3,Brandenburg,5014.4,3532.8,8276.5,0.298055,0.209991,0.491954,212.1,538.6,1314.2,...,1893.8,0.422179,0.200477,0.377344,96.4,73.3,252.7,0.228191,0.173558,0.598252
4,Bremen,1102.5,178.8,1236.8,0.437827,0.071004,0.491169,127.2,104.5,390.2,...,218.6,0.667753,0.002908,0.329339,63.9,38.0,158.6,0.245137,0.145911,0.608952

In [98]:
##'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

## create pmtiles

In [99]:
# def fgb_to_pmtiles_layer(polys_fgb, output_pmtiles, layer_name):
#     import subprocess
#     from pathlib import Path

#     subprocess.run([
#         "tippecanoe", "-o", str(Path(output_pmtiles).resolve()),
#         f"--layer={layer_name}",
#         "--minimum-zoom=5", "--maximum-zoom=7",
#         "--force",
#         "--no-feature-limit", "--no-tile-size-limit", 
#         "--drop-densest-as-needed",  # Nur Punkte entfernen, keine Vereinfachung
#         str(Path(polys_fgb).resolve())
#     ], check=True)

#     print("✅ Combined PMTiles created")

In [100]:
# ...existing code...
def fgb_to_pmtiles_layer(polys_fgb, output_pmtiles, layer_name, minzoom, maxzoom, include_fields=None):
    import subprocess
    from pathlib import Path

    cmd = [
        "tippecanoe",
        "-o", str(Path(output_pmtiles).resolve()),
        f"--layer={layer_name}",
        f"--minimum-zoom={minzoom}",
        f"--maximum-zoom={maxzoom}",
        "--force",
        "--read-parallel",
        "--detect-shared-borders",
        "--coalesce-densest-as-needed",
        "--extend-zooms-if-still-dropping",
    ]

    if include_fields:
        for f in include_fields:
            cmd += ["-y", f]

    cmd.append(str(Path(polys_fgb).resolve()))
    subprocess.run(cmd, check=True)

    print(f"✅ PMTiles created: {output_pmtiles}")
# ...existing code...

In [79]:
##### LANDKREISE

In [ ]:
kreise_wide = kreise[["Landkreis","geometry"]].merge(wide, on="Landkreis", how="left").fillna(0)
kreise_wide_4326=kreise_wide.to_crs(4326)
kreise_wide_4326.to_file("data/kreise_wide.fgb", driver="FlatGeobuf")

# Tippecanoe macht automatisch zoom-basierte Vereinfachung ohne Topologie-Probleme
fgb_to_pmtiles_layer(
    polys_fgb="data/kreise_wide.fgb",
    output_pmtiles="data/kreise_wide.pmtiles",
    layer_name="default",
    minzoom=5, 
    maxzoom=7
)

detected indexed FlatGeobuf: assigning feature IDs by sequence
434 features, 1107953 bytes of geometry and attributes, 163603 bytes of string pool, 0 bytes of vertices, 0 bytes of nodes

✅ PMTiles created: data/kreise_wide.pmtiles

  99.9%  7/67/43

In [45]:
##### BUDNESLAND

In [ ]:
# def fgb_to_pmtiles_layer(polys_fgb, output_pmtiles, layer_name):
#     import subprocess
#     from pathlib import Path

#     subprocess.run([
#         "tippecanoe", "-o", str(Path(output_pmtiles).resolve()),
#         f"--layer={layer_name}",
#         "--minimum-zoom=5", "--maximum-zoom=7",
#         "--force",
#         "--no-feature-limit", "--no-tile-size-limit", 
#         "--drop-densest-as-needed",  # Nur Punkte entfernen, keine Vereinfachung
#         str(Path(polys_fgb).resolve())
#     ], check=True)

#     print("✅ Combined PMTiles created")

In [101]:
bland_wide = bland[["Bundesland","geometry"]].merge(wide, on="Bundesland", how="left").fillna(0)

bland_wide_4326=bland_wide.to_crs(4326)

bland_wide_4326.to_file("data/bland_wide.fgb", driver="FlatGeobuf")

# Tippecanoe vereinfacht automatisch zoom-basiert
fgb_to_pmtiles_layer(
    polys_fgb="data/bland_wide.fgb",
    output_pmtiles="data/bland_wide.pmtiles",
    layer_name="default",
    minzoom=5, 
    maxzoom=7
)

detected indexed FlatGeobuf: assigning feature IDs by sequence
16 features, 495518 bytes of geometry and attributes, 14587 bytes of string pool, 0 bytes of vertices, 0 bytes of nodes

✅ PMTiles created: data/bland_wide.pmtiles

  99.9%  7/67/40